#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace civil_sheriff_scraper
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CivilSheriffScraper")]
	public partial class CSScraperDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAuctionDate(AuctionDate instance);
    partial void UpdateAuctionDate(AuctionDate instance);
    partial void DeleteAuctionDate(AuctionDate instance);
    partial void InsertAuction(Auction instance);
    partial void UpdateAuction(Auction instance);
    partial void DeleteAuction(Auction instance);
    #endregion
		
		public CSScraperDataContext() : 
				base(global::civil_sheriff_scraper.Properties.Settings.Default.CivilSheriffScraperConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CSScraperDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSScraperDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSScraperDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSScraperDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AuctionDate> AuctionDates
		{
			get
			{
				return this.GetTable<AuctionDate>();
			}
		}
		
		public System.Data.Linq.Table<Auction> Auctions
		{
			get
			{
				return this.GetTable<Auction>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AuctionDate")]
	public partial class AuctionDate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AuctionDateId;
		
		private string _StringDate;
		
		private System.DateTime _AuctionDateVal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuctionDateIdChanging(int value);
    partial void OnAuctionDateIdChanged();
    partial void OnStringDateChanging(string value);
    partial void OnStringDateChanged();
    partial void OnAuctionDateValChanging(System.DateTime value);
    partial void OnAuctionDateValChanged();
    #endregion
		
		public AuctionDate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuctionDateId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AuctionDateId
		{
			get
			{
				return this._AuctionDateId;
			}
			set
			{
				if ((this._AuctionDateId != value))
				{
					this.OnAuctionDateIdChanging(value);
					this.SendPropertyChanging();
					this._AuctionDateId = value;
					this.SendPropertyChanged("AuctionDateId");
					this.OnAuctionDateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StringDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string StringDate
		{
			get
			{
				return this._StringDate;
			}
			set
			{
				if ((this._StringDate != value))
				{
					this.OnStringDateChanging(value);
					this.SendPropertyChanging();
					this._StringDate = value;
					this.SendPropertyChanged("StringDate");
					this.OnStringDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuctionDateVal", DbType="Date NOT NULL")]
		public System.DateTime AuctionDateVal
		{
			get
			{
				return this._AuctionDateVal;
			}
			set
			{
				if ((this._AuctionDateVal != value))
				{
					this.OnAuctionDateValChanging(value);
					this.SendPropertyChanging();
					this._AuctionDateVal = value;
					this.SendPropertyChanged("AuctionDateVal");
					this.OnAuctionDateValChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auction")]
	public partial class Auction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AuctionId;
		
		private int _RealEstateId;
		
		private string _CaseNumber;
		
		private string _CaseTitle;
		
		private string _Address;
		
		private string _Attorney;
		
		private decimal _ClaimAmount;
		
		private bool _IsAppraised;
		
		private System.Nullable<System.DateTime> _WritAssignedDate;
		
		private System.Nullable<decimal> _WritAmount;
		
		private System.Nullable<bool> _WithAppraisal;
		
		private string _AssignedTo;
		
		private System.Nullable<bool> _IsStopped;
		
		private System.Nullable<System.DateTime> _AuctionDate;
		
		private System.Nullable<System.DateTime> _StoppedOn;
		
		private System.Nullable<System.DateTime> _PlaintiffDate;
		
		private System.Nullable<decimal> _PlaintiffAmount;
		
		private System.Nullable<System.DateTime> _DefendantDate;
		
		private System.Nullable<decimal> _DefendantAmount;
		
		private System.Nullable<System.DateTime> _RefereeDate;
		
		private System.Nullable<decimal> _RefereeAmount;
		
		private System.Nullable<decimal> _Lat;
		
		private System.Nullable<decimal> _Lng;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAuctionIdChanging(int value);
    partial void OnAuctionIdChanged();
    partial void OnRealEstateIdChanging(int value);
    partial void OnRealEstateIdChanged();
    partial void OnCaseNumberChanging(string value);
    partial void OnCaseNumberChanged();
    partial void OnCaseTitleChanging(string value);
    partial void OnCaseTitleChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnAttorneyChanging(string value);
    partial void OnAttorneyChanged();
    partial void OnClaimAmountChanging(decimal value);
    partial void OnClaimAmountChanged();
    partial void OnIsAppraisedChanging(bool value);
    partial void OnIsAppraisedChanged();
    partial void OnWritAssignedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnWritAssignedDateChanged();
    partial void OnWritAmountChanging(System.Nullable<decimal> value);
    partial void OnWritAmountChanged();
    partial void OnWithAppraisalChanging(System.Nullable<bool> value);
    partial void OnWithAppraisalChanged();
    partial void OnAssignedToChanging(string value);
    partial void OnAssignedToChanged();
    partial void OnIsStoppedChanging(System.Nullable<bool> value);
    partial void OnIsStoppedChanged();
    partial void OnAuctionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAuctionDateChanged();
    partial void OnStoppedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnStoppedOnChanged();
    partial void OnPlaintiffDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPlaintiffDateChanged();
    partial void OnPlaintiffAmountChanging(System.Nullable<decimal> value);
    partial void OnPlaintiffAmountChanged();
    partial void OnDefendantDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDefendantDateChanged();
    partial void OnDefendantAmountChanging(System.Nullable<decimal> value);
    partial void OnDefendantAmountChanged();
    partial void OnRefereeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRefereeDateChanged();
    partial void OnRefereeAmountChanging(System.Nullable<decimal> value);
    partial void OnRefereeAmountChanged();
    partial void OnLatChanging(System.Nullable<decimal> value);
    partial void OnLatChanged();
    partial void OnLngChanging(System.Nullable<decimal> value);
    partial void OnLngChanged();
    #endregion
		
		public Auction()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuctionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AuctionId
		{
			get
			{
				return this._AuctionId;
			}
			set
			{
				if ((this._AuctionId != value))
				{
					this.OnAuctionIdChanging(value);
					this.SendPropertyChanging();
					this._AuctionId = value;
					this.SendPropertyChanged("AuctionId");
					this.OnAuctionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealEstateId", DbType="Int NOT NULL")]
		public int RealEstateId
		{
			get
			{
				return this._RealEstateId;
			}
			set
			{
				if ((this._RealEstateId != value))
				{
					this.OnRealEstateIdChanging(value);
					this.SendPropertyChanging();
					this._RealEstateId = value;
					this.SendPropertyChanged("RealEstateId");
					this.OnRealEstateIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CaseNumber
		{
			get
			{
				return this._CaseNumber;
			}
			set
			{
				if ((this._CaseNumber != value))
				{
					this.OnCaseNumberChanging(value);
					this.SendPropertyChanging();
					this._CaseNumber = value;
					this.SendPropertyChanged("CaseNumber");
					this.OnCaseNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaseTitle", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CaseTitle
		{
			get
			{
				return this._CaseTitle;
			}
			set
			{
				if ((this._CaseTitle != value))
				{
					this.OnCaseTitleChanging(value);
					this.SendPropertyChanging();
					this._CaseTitle = value;
					this.SendPropertyChanged("CaseTitle");
					this.OnCaseTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attorney", DbType="NVarChar(255)")]
		public string Attorney
		{
			get
			{
				return this._Attorney;
			}
			set
			{
				if ((this._Attorney != value))
				{
					this.OnAttorneyChanging(value);
					this.SendPropertyChanging();
					this._Attorney = value;
					this.SendPropertyChanged("Attorney");
					this.OnAttorneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaimAmount", DbType="Decimal(18,2) NOT NULL")]
		public decimal ClaimAmount
		{
			get
			{
				return this._ClaimAmount;
			}
			set
			{
				if ((this._ClaimAmount != value))
				{
					this.OnClaimAmountChanging(value);
					this.SendPropertyChanging();
					this._ClaimAmount = value;
					this.SendPropertyChanged("ClaimAmount");
					this.OnClaimAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAppraised", DbType="Bit NOT NULL")]
		public bool IsAppraised
		{
			get
			{
				return this._IsAppraised;
			}
			set
			{
				if ((this._IsAppraised != value))
				{
					this.OnIsAppraisedChanging(value);
					this.SendPropertyChanging();
					this._IsAppraised = value;
					this.SendPropertyChanged("IsAppraised");
					this.OnIsAppraisedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WritAssignedDate", DbType="Date")]
		public System.Nullable<System.DateTime> WritAssignedDate
		{
			get
			{
				return this._WritAssignedDate;
			}
			set
			{
				if ((this._WritAssignedDate != value))
				{
					this.OnWritAssignedDateChanging(value);
					this.SendPropertyChanging();
					this._WritAssignedDate = value;
					this.SendPropertyChanged("WritAssignedDate");
					this.OnWritAssignedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WritAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> WritAmount
		{
			get
			{
				return this._WritAmount;
			}
			set
			{
				if ((this._WritAmount != value))
				{
					this.OnWritAmountChanging(value);
					this.SendPropertyChanging();
					this._WritAmount = value;
					this.SendPropertyChanged("WritAmount");
					this.OnWritAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WithAppraisal", DbType="Bit")]
		public System.Nullable<bool> WithAppraisal
		{
			get
			{
				return this._WithAppraisal;
			}
			set
			{
				if ((this._WithAppraisal != value))
				{
					this.OnWithAppraisalChanging(value);
					this.SendPropertyChanging();
					this._WithAppraisal = value;
					this.SendPropertyChanged("WithAppraisal");
					this.OnWithAppraisalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedTo", DbType="NVarChar(50)")]
		public string AssignedTo
		{
			get
			{
				return this._AssignedTo;
			}
			set
			{
				if ((this._AssignedTo != value))
				{
					this.OnAssignedToChanging(value);
					this.SendPropertyChanging();
					this._AssignedTo = value;
					this.SendPropertyChanged("AssignedTo");
					this.OnAssignedToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsStopped", DbType="Bit")]
		public System.Nullable<bool> IsStopped
		{
			get
			{
				return this._IsStopped;
			}
			set
			{
				if ((this._IsStopped != value))
				{
					this.OnIsStoppedChanging(value);
					this.SendPropertyChanging();
					this._IsStopped = value;
					this.SendPropertyChanged("IsStopped");
					this.OnIsStoppedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuctionDate", DbType="Date")]
		public System.Nullable<System.DateTime> AuctionDate
		{
			get
			{
				return this._AuctionDate;
			}
			set
			{
				if ((this._AuctionDate != value))
				{
					this.OnAuctionDateChanging(value);
					this.SendPropertyChanging();
					this._AuctionDate = value;
					this.SendPropertyChanged("AuctionDate");
					this.OnAuctionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoppedOn", DbType="Date")]
		public System.Nullable<System.DateTime> StoppedOn
		{
			get
			{
				return this._StoppedOn;
			}
			set
			{
				if ((this._StoppedOn != value))
				{
					this.OnStoppedOnChanging(value);
					this.SendPropertyChanging();
					this._StoppedOn = value;
					this.SendPropertyChanged("StoppedOn");
					this.OnStoppedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaintiffDate", DbType="Date")]
		public System.Nullable<System.DateTime> PlaintiffDate
		{
			get
			{
				return this._PlaintiffDate;
			}
			set
			{
				if ((this._PlaintiffDate != value))
				{
					this.OnPlaintiffDateChanging(value);
					this.SendPropertyChanging();
					this._PlaintiffDate = value;
					this.SendPropertyChanged("PlaintiffDate");
					this.OnPlaintiffDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaintiffAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PlaintiffAmount
		{
			get
			{
				return this._PlaintiffAmount;
			}
			set
			{
				if ((this._PlaintiffAmount != value))
				{
					this.OnPlaintiffAmountChanging(value);
					this.SendPropertyChanging();
					this._PlaintiffAmount = value;
					this.SendPropertyChanged("PlaintiffAmount");
					this.OnPlaintiffAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefendantDate", DbType="Date")]
		public System.Nullable<System.DateTime> DefendantDate
		{
			get
			{
				return this._DefendantDate;
			}
			set
			{
				if ((this._DefendantDate != value))
				{
					this.OnDefendantDateChanging(value);
					this.SendPropertyChanging();
					this._DefendantDate = value;
					this.SendPropertyChanged("DefendantDate");
					this.OnDefendantDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefendantAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> DefendantAmount
		{
			get
			{
				return this._DefendantAmount;
			}
			set
			{
				if ((this._DefendantAmount != value))
				{
					this.OnDefendantAmountChanging(value);
					this.SendPropertyChanging();
					this._DefendantAmount = value;
					this.SendPropertyChanged("DefendantAmount");
					this.OnDefendantAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeDate", DbType="Date")]
		public System.Nullable<System.DateTime> RefereeDate
		{
			get
			{
				return this._RefereeDate;
			}
			set
			{
				if ((this._RefereeDate != value))
				{
					this.OnRefereeDateChanging(value);
					this.SendPropertyChanging();
					this._RefereeDate = value;
					this.SendPropertyChanged("RefereeDate");
					this.OnRefereeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefereeAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> RefereeAmount
		{
			get
			{
				return this._RefereeAmount;
			}
			set
			{
				if ((this._RefereeAmount != value))
				{
					this.OnRefereeAmountChanging(value);
					this.SendPropertyChanging();
					this._RefereeAmount = value;
					this.SendPropertyChanged("RefereeAmount");
					this.OnRefereeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this.OnLngChanging(value);
					this.SendPropertyChanging();
					this._Lng = value;
					this.SendPropertyChanged("Lng");
					this.OnLngChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
